 ## EDA to Justify Validity of Proposed Feature Transform

### Imports and Reading in Data

In [ ]:
import pandas as pd
import numpy as np
% matplotlib inline

In [3]:
train = pd.read_csv("train.csv")

In [4]:
len(train)

250874

In [5]:
train.head()

ex_id  user_id  prod_id  rating  label        date  \
0      0      923        0     3.0      1  2014-12-08   
1      1      924        0     3.0      1  2013-05-16   
2      2      925        0     4.0      1  2013-07-01   
3      3      926        0     4.0      1  2011-07-28   
4      4      927        0     4.0      1  2010-11-01   

                                              review  
0  The food at snack is a selection of popular Gr...  
1  This little place in Soho is wonderful. I had ...  
2  ordered lunch for 15 from Snack last Friday.  ...  
3  This is a beautiful quaint little restaurant o...  
4  Snack is great place for a  casual sit down lu...

In [34]:
train.user_id.nunique()

125679

The first thing we want to do is understand how much user repetition there is in our dataset. 

### Exploring Dataset for User Counts

In [6]:
counts = pd.DataFrame(train.user_id.value_counts()).reset_index()
counts.columns = ["id","count"]
counts.head()

id  count
0  3504    121
1  2980     99
2  3459     84
3  1011     82
4  3324     81

In [7]:
len(counts)

125679

In [8]:
for i in range(1,11):
    subset = counts[counts['count']>i]
    proportion = (len(subset) / len(counts))*100
    print("The amount of users with more than",i,"review(s) make up",proportion,"% of the dataset")
    

The amount of users with more than 1 review(s) make up 30.643942106477613 % of the dataset
The amount of users with more than 2 review(s) make up 15.833989767582493 % of the dataset
The amount of users with more than 3 review(s) make up 9.942790760588483 % of the dataset
The amount of users with more than 4 review(s) make up 6.911258046292539 % of the dataset
The amount of users with more than 5 review(s) make up 5.167132138225162 % of the dataset
The amount of users with more than 6 review(s) make up 4.0961497147494805 % of the dataset
The amount of users with more than 7 review(s) make up 3.320363783925716 % of the dataset
The amount of users with more than 8 review(s) make up 2.742701644666173 % of the dataset
The amount of users with more than 9 review(s) make up 2.3313361818601357 % of the dataset
The amount of users with more than 10 review(s) make up 1.994764439564287 % of the dataset


Now let's see how the label distribution changes as we filter by # of reviews

### Checking Label Distribution Based on Filtering By # of Reviews

In [9]:
train.label.value_counts(normalize=True)

/Users/Aren/anaconda/lib/python3.5/site-packages/pandas/compat/_optional.py:106: UserWarning: Pandas requires version '2.6.2' or newer of 'numexpr' (version '2.6.1' currently installed).
  warnings.warn(msg, UserWarning)


0    0.897084
1    0.102916
Name: label, dtype: float64

In [10]:
for j in [1,5,10,15,20,100]:
    print("-----------------------------------------------------")
    print("LABEL DISTRIBUTION DELETING USERS WITH <=",j,"REVIEWS")
    copy = train.copy()
    filtered = counts[counts['count']<=j]
    print("size of counts df reduced from",len(counts),"to",len(filtered))
    toDelete = filtered['id'].tolist()
    print("We are deleting",len(toDelete),"users")
    print("Original training size:",len(copy))
    copy = copy[~copy['user_id'].isin(toDelete)]
    print("New training size:",len(copy))
    print(copy.label.value_counts(normalize=True))
    print("-----------------------------------------------------")

-----------------------------------------------------
LABEL DISTRIBUTION DELETING USERS WITH <= 1 REVIEWS
size of counts df reduced from 125679 to 87166
We are deleting 87166 users
Original training size: 250874
New training size: 163708
0    0.952256
1    0.047744
Name: label, dtype: float64
-----------------------------------------------------
-----------------------------------------------------
LABEL DISTRIBUTION DELETING USERS WITH <= 5 REVIEWS
size of counts df reduced from 125679 to 119185
We are deleting 119185 users
Original training size: 250874
New training size: 78070
0    0.980236
1    0.019764
Name: label, dtype: float64
-----------------------------------------------------
-----------------------------------------------------
LABEL DISTRIBUTION DELETING USERS WITH <= 10 REVIEWS
size of counts df reduced from 125679 to 123172
We are deleting 123172 users
Original training size: 250874
New training size: 48478
0    0.9816
1    0.0184
Name: label, dtype: float64
-----------

### Summary of Results and Appropriate Data Transformation

We found a "splitting criterion" of approximately 5 reviews that changes the label balance significantly. However, implementing this fact alone into our dataset might cause some problems, so an alternative approach to encode this information is discussed below. 

Thinking about the training set at the granularity of a single instance, it would be data leakage to simply add a column that simply gives the total # of reviews given by a user in the set. Luckily, we can use the <i>date </i> column to instead give us the <b> number of reviews by the user up to the date of the current instance </b>, which will circumvent the data leakage issue and still encode what we believe to be (using evidence from above) a feature with fairly significant predictive power. 

## Implementation of Feature Transform

In [73]:
def engineered_df(df):
    rolling_rev = []
    user_dict = {}
    for index,row in df.iterrows():
        curr_date = row['date']
        curr_user = row['user_id']
        
        if(curr_user not in user_dict):
            dates = df.loc[df.user_id == curr_user,'date'].tolist()
            dates.sort()
            user_dict[curr_user] = dates
        index = user_dict[curr_user].index(curr_date)
        
        rolling_rev.append(index+1)
        
    df['reviewsToDate'] = rolling_rev
    return df
        
        
        

In [79]:
transformed_df = engineered_df(train)

In [80]:
transformed_df.head(10)

ex_id  user_id  prod_id  rating  label        date  \
0      0      923        0     3.0      1  2014-12-08   
1      1      924        0     3.0      1  2013-05-16   
2      2      925        0     4.0      1  2013-07-01   
3      3      926        0     4.0      1  2011-07-28   
4      4      927        0     4.0      1  2010-11-01   
5      5      928        0     4.0      1  2009-09-02   
6      7      930        0     4.0      1  2007-05-20   
7      8      931        0     4.0      1  2005-12-27   
8     10      933        0     5.0      1  2014-01-21   
9     12      935        0     5.0      1  2011-01-31   

                                              review  reviewsToDate  
0  The food at snack is a selection of popular Gr...             25  
1  This little place in Soho is wonderful. I had ...              1  
2  ordered lunch for 15 from Snack last Friday.  ...              1  
3  This is a beautiful quaint little restaurant o...              1  
4  Snack is great place for a  casual sit down lu...              2  
5  A solid 4 stars for this greek food spot.  If ...              1  
6  Love this place!  Try the Chicken sandwich or ...              1  
7  My friend and I were intrigued by the nightly ...             14  
8        pretty cool place...good food...good people              1  
9  Fabulous Authentic Greek Food!!! This little s...              1

### Sanity Check 

In the first 10 rows, we see 3 users: 923, 927, and 931 who have a reviewsToDate value > 1. Let's verify these results.

In [82]:
train[train['user_id']==923].sort_values(by=['date'])

ex_id  user_id  prod_id  rating  label        date  \
202384  289603      923      759     5.0      1  2013-11-04   
122365  174979      923      131     5.0      1  2013-11-11   
172282  246460      923      906     5.0      1  2013-11-19   
166153  237627      923      622     5.0      1  2013-11-19   
81951   117298      923      675     5.0      1  2014-01-04   
129686  185412      923      505     5.0      1  2014-01-04   
4180      5992      923       19     5.0      1  2014-01-14   
50805    72648      923      649     5.0      1  2014-02-12   
128545  183766      923      502     5.0      1  2014-02-12   
182849  261658      923      337     5.0      1  2014-02-18   
29356    41894      923      100     4.0      1  2014-03-05   
37708    53903      923      133     5.0      1  2014-03-05   
204847  293098      923      741     5.0      1  2014-03-05   
20800    29654      923       79     3.0      1  2014-03-30   
9072     12853      923       40     4.0      1  2014-05-30   
95818   137121      923      400     5.0      1  2014-07-07   
90666   129738      923      376     4.0      1  2014-07-07   
31815    45404      923      103     5.0      1  2014-07-28   
136094  194629      923      420     5.0      1  2014-08-25   
21641    30833      923       81     4.0      1  2014-09-28   
190430  272462      923      710     4.0      1  2014-10-07   
152833  218543      923      572     4.0      1  2014-10-07   
42090    60145      923      152     5.0      1  2014-11-13   
113143  161807      923      456     4.0      1  2014-11-13   
0            0      923        0     3.0      1  2014-12-08   
232937  333266      923      880     3.0      1  2014-12-08   

                                                   review  reviewsToDate  
202384  The falafel were superb, stuffed grape leaved ...              1  
122365  The food is simply excellent. Everything is as...              2  
172282  I had Nasi Lemak and Nyonya Seafood Fried Rice...              3  
166153  This place is amazing.We really love good lati...              3  
81951   I recently ate at Olea again and continue to b...              5  
129686  I was in the neighborhood with out-of-town gue...              5  
4180    The restaurant is on the ground floor of a typ...              7  
50805   This restaurant was quite a pleasant surprise....              8  
128545  The crab and pork noodles is delicious!!! I re...              8  
182849  My husband and I went to this restaurant for a...             10  
29356   Clinton street baking is a super popular baker...             11  
37708   The Tom's Restaurant is the outside shot of th...             11  
204847  This is a super little spot for brunch. Quaint...             11  
20800   We ate at the Blue Ribbon with colleagues. The...             14  
9072    Really nice mousaka and lovely décor inside. A...             15  
95818   This place has amazing tacos. The sopes are pr...             16  
90666   I always visit if in the mood for a hearty Pol...             16  
31815   Thiru has wonderful personality. He has a very...             18  
136094  We had a lovely meal on a Friday night at Marc...             19  
21641   I loved the antibiotic- and hormone-free chick...             20  
190430  The Post Office is a friendly place. The staff...             21  
152833  Tried the huge slices with some of my friends ...             21  
42090   Great food and wine! Waitress was super helpfu...             23  
113143  Basso56 was very crowded with the theatre crow...             23  
0       The food at snack is a selection of popular Gr...             25  
232937  Salads are good. Prices are good. Pesto lasagn...             25

In [83]:
train[train['user_id']==927].sort_values(by=['date'])

ex_id  user_id  prod_id  rating  label        date  \
130005  185887      927      540     5.0      1  2010-10-24   
4            4      927        0     4.0      1  2010-11-01   
120874  172833      927      470     4.0      1  2010-11-22   

                                                   review  reviewsToDate  
130005  By far one of my favorite restaurants in the c...              1  
4       Snack is great place for a  casual sit down lu...              2  
120874  One of the BEST brunches I have had in the cit...              3

In [84]:
train[train['user_id']==931].sort_values(by=['date'])

ex_id  user_id  prod_id  rating  label        date  \
19817    28217      931       78     5.0      1  2005-11-03   
20823    29684      931       79     4.0      1  2005-11-08   
204552  292709      931      766     5.0      1  2005-12-06   
1173      1676      931        7     3.0      1  2005-12-08   
228393  326747      931      860     4.0      1  2005-12-09   
115455  165136      931      465     5.0      1  2005-12-12   
239312  342337      931      901     4.0      1  2005-12-13   
193841  277404      931      723     5.0      1  2005-12-13   
52140    74496      931      209     4.0      1  2005-12-13   
107338  153559      931      442     4.0      1  2005-12-13   
114048  163125      931      692     4.0      1  2005-12-15   
235976  337563      931      890     5.0      1  2005-12-15   
107976  154411      931      444     3.0      1  2005-12-21   
7            8      931        0     4.0      1  2005-12-27   
10117    14354      931       43     5.0      1  2005-12-27   
70082   100144      931      277     4.0      1  2005-12-29   
172304  246487      931      906     5.0      1  2006-01-12   
14536    20650      931       63     5.0      1  2006-01-12   
2276      3304      931      490     4.0      1  2006-01-12   
229073  327739      931      792     4.0      1  2006-01-12   
34188    48839      931      308     4.0      1  2006-01-13   
46514    66573      931      177     5.0      1  2006-01-13   

                                                   review  reviewsToDate  
19817   If you have a large group in New York, then th...              1  
20823   Any restaurant that you can go into at 2 am an...              2  
204552  Walking in on a cold fall night, it is not har...              3  
1173    Very good food in a very casual atmosphere for...              4  
228393  My cousin and I went to grab a drink on Stone ...              5  
115455  I honestly do not understand how anyone can no...              6  
239312  In order to get tapas and a small table you wi...              7  
193841  I've been to Alta five times since they opened...              7  
52140   Their wings are great and they make them hot! ...              7  
107338  Song is fabulous, even better than the origina...              7  
114048  I noticed this place while sitting in traffic ...             11  
235976  If you're out drinking and you're looking for ...             11  
107976  When they say NYC restaurants are small, they ...             13  
7       My friend and I were intrigued by the nightly ...             14  
10117   WOW! What a great restaurant. Food, decor and ...             14  
70082   I was walking around and without knowing about...             16  
172304  Nyonya is probably the only authentic restaura...             17  
14536   I have been to Jane several times for brunch a...             17  
2276    I've been here numerous times for the tasting ...             17  
229073  We celebrated my cousin's 24th birthday at thi...             17  
34188   Since we were a fairly large party, we were re...             21  
46514   You think you've lived here long enough and kn...             21